services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "8081:8080"
    depends_on:
      - inventory-service
    networks:
      - default

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8082:8080"
    networks:
      - default

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - order-service
      - inventory-service
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - default

networks:
  default:
    name: ICE2_default

