spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://inventory-service:8080
          predicates:
            - Path=/inventory/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


server:
  port: 8083